# Site settings
title:       "Israel Apartheid-Annexation"
description: "A Letter on Annexation and Apartheid in Israel."
baseurl:     ""
url:         "https://www.annexation.site"
date_format: "%b %-d, %Y"
#header_pages:
 #- about.md


google_analytics:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname:

# Social icons
#github_username: saikiransripada
#twitter_username: wp_user
#linkedin_username: saikiransripada
#dev_username: dev_user

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
#share_googleplus: false
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
    post_footer:    'A Letter on Annexation and Apartheid in Israel.'
  index:
    coming_soon: 'A Letter on Annexation and Apartheid in Israel.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor

# Comments
staticman_url: https://annexationsitebot.herokuapp.com/v2/connect/adamdjbrett/annexation-option2/master/comments

#recaptcha
reCaptcha:
  siteKey: "6LfuigEVAAAAANCztc6of-H02PEY7ygI1_Sthg63"
  # Encrypt reCaptcha secret key using Staticman /encrypt endpoint
  # For more information, https://staticman.net/docs/encryption
  secret: "sBioYSfdDC4vlyrSh3naY1tpUJpEbXECKofHTnfwHqEhV56BiQERXGO9J1dKe1AAiK/tD85PelgdV5Sk2Ut+n/6DXY7C2zpq4KQ9do6off8ebZqtSrjTuWNIUc1ePJrWBqxWLCXaaFLQ2/G74skJrL1E4U+syUqWUH9GhCWgiT8nkBPorFQdiMBva3XS/4UK1++2mqsMcvcnzZwOb4ii8Kxj5AhSqKnsMLNLocypXju4LfiRN5h/8USjTGFXGh/PorsBZ/cZGquvn4Wohds6GSLWAq8/quPqdyKDp7JcttyJF9vxebkNeHoj04549MUs20UEF89jzCKZyBaoGmJiqOLHDfmOhHvfAe29wMhnP1QXsVUPzVYM/CTFRLFFVtmmwo1uXNwUo9piVp9UEnX25rg2gTj6gX+swKAsKX/9poleTgteHW+TyOHx2n/dJZnOlLh+AE8g1rA/If88z/2JvOQnPwO7w5iUxwa59eua9VR0/DjTegu/GoBcnnhwq+4tHwdPC3YNFLB3dacEYoqUJmlK3h61YQNEM5G9okQkwgzG9QFz+zou4QnI6g7Hdzb4UBFK0X/9z9fBHYhe4Dv/nEjHVsviDnU0IB1nw15lwEeU3zDbm6kn6N0eOVkORDM9q7xe9x+WFs0QdPrSvVrRY4DxwtB5A37jyVX/nu28PWc="
